name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack yarn pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: backend
      - name: Generate Prisma client
        run: pnpm run prisma:generate
        working-directory: backend
      - name: Run lint
        run: pnpm run lint
        working-directory: backend
      - name: Run typecheck
        run: pnpm run typecheck
        working-directory: backend
      - name: Run tests
        run: pnpm run test
        working-directory: backend
